name: Deploy Infrastructure

on:
  push:
    branches:
      - infrastructure

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-1
      run: terraform init -input=false
      working-directory: ./terraform

    - name: Terraform validation
      run: terraform validate
      working-directory: ./terraform
      
    - name: Terraform show
      run: terraform show
      working-directory: ./terraform

#     - name: Terraform apply 
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_DEFAULT_REGION: ap-southeast-1
#       working-directory: ./terraform
#       run: terraform apply -auto-approve -input=false -var="github_token=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"
