name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build
        run: |
          pwd
          echo "Go into code and create package..."
          cd terraform/code
          mkdir package
          pip install --target ./package -r requirements_dev.txt
          echo "Create build folder..."
          rm -rf ../build
          mkdir ../build
          echo "Zip package directory..."
          cd package
          zip -r ../../build/${{ github.run_id }}.zip .
          echo "Add handler.py into zip package..."
          cd ..
          zip -g ../build/${{ github.run_id }}.zip handler.py
          echo "Return to root folder..."
          cd ..

      - name: Upload to S3
        run: aws s3 cp terraform/build/${{ github.run_id }}.zip s3://${{ secrets.S3_BUCKET_NAME }}/${{ github.run_id }}.zip

      - name: Update lambda function code
        run: aws lambda update-function-code --function-name test-file-upload --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key ${{ github.run_id }}.zip

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Release lambda function version
        run: aws lambda publish-version --function-name test-file-upload --description ${{ github.run_id }}
