name: Exclusion Service CI/CD

on:
  push:
    branches:
      - "microservices"
    paths:
      - "code/services/exclusion_service.py"
      - ".github/workflows/exclusion_service_cicd.yaml"
      - ".github/workflows/cd.yaml"
  pull_request:
    branches:
      - "microservices"

jobs:
  # ci:
  #   uses: ./.github/workflows/ci.yaml
  #   with:
  #     source-path: code/services

  cd:
    uses: ./.github/workflows/cd.yaml
    # needs: [ci]
    with:
      s3-folder-name: exclusion
      src-file-name: exclusion_service
      lambda-name: exclusion_service
