name: Exclusion Service CI/CD

on:
  push:
    branches:
      - "project-2022-23t1-g1-team1-microservices"
    paths:
      - "code/services/exclusion_service.py"
  pull_request:
    branches:
      - "project-2022-23t1-g1-team1-microservices"

jobs:
  # ci:
  #   uses: ./.github/workflows/ci.yaml
  #   with:
  #     source-path: code/services

  cd:
    uses: ./.github/workflows/cd.yaml
    # needs: [ci]
    with:
      s3-folder-name: exclusion
      src-file-dir: code/services
      src-file-name: exclusion_service
      lambda-name: exclusion_service
    secrets: inherit
