name: Health Check CI/CD

on:
  push:
    branches:
      - "project-2022-23t1-g1-team1-feature/health"
    paths:
      - "code/health/health_check.py"
  pull_request:
    branches:
      - "project-2022-23t1-g1-team1-feature/health"

jobs:
  # ci:
  #   uses: ./.github/workflows/ci.yaml
  #   with:
  #     source-path: code/health

  cd:
    uses: ./.github/workflows/cd.yaml
    # needs: [ci]
    with:
      s3-folder-name: health
      src-file-dir: code/health
      src-file-name: health_check
      lambda-name: health_check
    secrets: inherit
