name: Process CSV CI/CD

on:
  push:
    branches:
      - "feature/process-csv"
  pull_request:
    branches:
      - "feature/process-csv"

env:
  SG_S3_BUCKET_NAME: lambda-archive-g1t1-singapore
  NV_S3_BUCKET_NAME: lambda-archive-g1t1-north-virginia
  CSV_PROCESSOR_LAMBDA_NAME: file-upload
  STEPFUNCTION_TRIGGER_LAMBDA_NAME: stepfunction-trigger

jobs:
  ci:
    uses: ./.github/workflows/process_csv_ci.yaml
    with:
      source-path: code/process_csv

  build:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Create Build folder
        run: |
          rm -rf build
          mkdir build

      - name: Zip Code Files
        run: |
          cd code/process_csv
          zip ../../build/csv_processor-${{ github.run_id }}.zip csv_processor.py
          zip ../../build/stepfunction_trigger-${{ github.run_id }}.zip stepfunction_trigger.py

      - name: Add Required Packages
        run: |
          cd code/process_csv
          mkdir package
          pip install --target ./package -r requirements_dev.txt
          cd package
          if [ "$(ls)" ]; then
            zip -g -r ../../../build/csv_processor-${{ github.run_id }}.zip .
            zip -g -r ../../../build/stepfunction_trigger-${{ github.run_id }}.zip .
          fi

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/

  deploy-sg:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload to S3
        run: |
          echo "Update Singapore S3"
          aws s3 cp build-files/csv_processor-${{ github.run_id }}.zip s3://${{ env.SG_S3_BUCKET_NAME }}/csv_processor/${{ github.run_id }}.zip
          aws s3 cp build-files/stepfunction_trigger-${{ github.run_id }}.zip s3://${{ env.SG_S3_BUCKET_NAME }}/stepfunction_trigger/${{ github.run_id }}.zip

      - name: Update lambda function code
        run: |
          echo "Update Singapore Lambda Function"
          aws lambda update-function-code --function-name ${{ env.CSV_PROCESSOR_LAMBDA_NAME }} --s3-bucket ${{ env.SG_S3_BUCKET_NAME }} --s3-key csv_processor/${{ github.run_id }}.zip
          aws lambda update-function-code --function-name ${{ env.STEPFUNCTION_TRIGGER_LAMBDA_NAME }} --s3-bucket ${{ env.SG_S3_BUCKET_NAME }} --s3-key stepfunction_trigger/${{ github.run_id }}.zip

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Release lambda function version
        run: |
          aws lambda publish-version --function-name ${{ env.CSV_PROCESSOR_LAMBDA_NAME }} --description ${{ github.run_id }}
          aws lambda publish-version --function-name ${{ env.STEPFUNCTION_TRIGGER_LAMBDA_NAME }} --description ${{ github.run_id }}

  deploy-nv:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          echo "Update North Virginia S3"
          aws s3 cp build-files/csv_processor-${{ github.run_id }}.zip s3://${{ env.NV_S3_BUCKET_NAME }}/csv_processor/${{ github.run_id }}.zip
          aws s3 cp build-files/stepfunction_trigger-${{ github.run_id }}.zip s3://${{ env.NV_S3_BUCKET_NAME }}/stepfunction_trigger/${{ github.run_id }}.zip

      - name: Update lambda function code
        run: |
          echo "Update North Virginia Lambda Function"
          aws lambda update-function-code --function-name ${{ env.CSV_PROCESSOR_LAMBDA_NAME }} --s3-bucket ${{ env.NV_S3_BUCKET_NAME }} --s3-key csv_processor/${{ github.run_id }}.zip
          aws lambda update-function-code --function-name ${{ env.STEPFUNCTION_TRIGGER_LAMBDA_NAME }} --s3-bucket ${{ env.NV_S3_BUCKET_NAME }} --s3-key stepfunction_trigger/${{ github.run_id }}.zip

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Release lambda function version
        run: |
          aws lambda publish-version --function-name ${{ env.CSV_PROCESSOR_LAMBDA_NAME }} --description ${{ github.run_id }}
          aws lambda publish-version --function-name ${{ env.STEPFUNCTION_TRIGGER_LAMBDA_NAME }} --description ${{ github.run_id }}
