name: Transaction Service CI/CD

on:
  push:
    branches:
      - "microservices"
    paths:
      - "code/services/transaction_service.py"
      - ".github/workflows/transaction_service_cicd.yaml"
  pull_request:
    branches:
      - "microservices"

jobs:
  # ci:
  #   uses: ./.github/workflows/ci.yaml
  #   with:
  #     source-path: code/services

  cd:
    uses: ./.github/workflows/cd.yaml
    # needs: [ci]
    with:
      s3-folder-name: transaction
      src-file-dir: code/services
      src-file-name: transaction_service
      lambda-name: transaction_service
    secrets: inherit
